### ISSUE TITLE
Query "more_like_this"

### ISSUE THREAD

**Issue by wachterjohannes** [pucene/old#13]
https://www.elastic.co/guide/en/elasticsearch/reference/2.4/query-dsl-mlt-query.html

- [x] Basic implementation #11 
- [x] `fields` (#11)
- [ ] without `fields` (`_all` field - see issue https://github.com/pucene/pucene/issues/20)
- [x] `like` (#11)
  - Text
  - Document
  - Artificial documents
- [ ] `unlike`
- [x] `min_term_freq` (#11)
- [x] `max_query_terms`  (#11)
- [x] `min_doc_freq` (#11)
- [ ] `max_doc_freq`
- [ ] `min_word_length`
- [ ] `max_word_length`
- [ ] `stop_words`
- [ ] `analyzer`
- [ ] `minimum_should_match`
- [ ] `boost_terms`
- [ ] `include`
- [ ] `boost`
